apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pgxdlvnmx-go 
  janus-idp.io/tekton: pgxdlvnmx-go
  backstage.io/kubernetes-id: pgxdlvnmx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pgxdlvnmx-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml